# Generated by Django 3.2.9 on 2022-07-21 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usertariff_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertariff',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 20, 11, 4, 46, 168247), verbose_name='Finish date'),
        ),
    ]
